package com.lcbo.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lcbo.model.db.Cart;
import com.lcbo.model.db.Product;
import com.lcbo.model.db.Store;
import com.lcbo.model.db.StoreProductRelation;

import com.lcbo.model.db.CartDao;
import com.lcbo.model.db.ProductDao;
import com.lcbo.model.db.StoreDao;
import com.lcbo.model.db.StoreProductRelationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cartDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig storeDaoConfig;
    private final DaoConfig storeProductRelationDaoConfig;

    private final CartDao cartDao;
    private final ProductDao productDao;
    private final StoreDao storeDao;
    private final StoreProductRelationDao storeProductRelationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cartDaoConfig = daoConfigMap.get(CartDao.class).clone();
        cartDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        storeDaoConfig = daoConfigMap.get(StoreDao.class).clone();
        storeDaoConfig.initIdentityScope(type);

        storeProductRelationDaoConfig = daoConfigMap.get(StoreProductRelationDao.class).clone();
        storeProductRelationDaoConfig.initIdentityScope(type);

        cartDao = new CartDao(cartDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        storeDao = new StoreDao(storeDaoConfig, this);
        storeProductRelationDao = new StoreProductRelationDao(storeProductRelationDaoConfig, this);

        registerDao(Cart.class, cartDao);
        registerDao(Product.class, productDao);
        registerDao(Store.class, storeDao);
        registerDao(StoreProductRelation.class, storeProductRelationDao);
    }
    
    public void clear() {
        cartDaoConfig.clearIdentityScope();
        productDaoConfig.clearIdentityScope();
        storeDaoConfig.clearIdentityScope();
        storeProductRelationDaoConfig.clearIdentityScope();
    }

    public CartDao getCartDao() {
        return cartDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public StoreDao getStoreDao() {
        return storeDao;
    }

    public StoreProductRelationDao getStoreProductRelationDao() {
        return storeProductRelationDao;
    }

}
