package com.lcbo.model.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STORE_PRODUCT_RELATION".
*/
public class StoreProductRelationDao extends AbstractDao<StoreProductRelation, Long> {

    public static final String TABLENAME = "STORE_PRODUCT_RELATION";

    /**
     * Properties of entity StoreProductRelation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StoreId = new Property(1, Long.class, "storeId", false, "STORE_ID");
        public final static Property ProductId = new Property(2, Long.class, "productId", false, "PRODUCT_ID");
        public final static Property RelationId = new Property(3, String.class, "relationId", false, "RELATION_ID");
    }


    public StoreProductRelationDao(DaoConfig config) {
        super(config);
    }
    
    public StoreProductRelationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STORE_PRODUCT_RELATION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"STORE_ID\" INTEGER," + // 1: storeId
                "\"PRODUCT_ID\" INTEGER," + // 2: productId
                "\"RELATION_ID\" TEXT UNIQUE );"); // 3: relationId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STORE_PRODUCT_RELATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StoreProductRelation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long storeId = entity.getStoreId();
        if (storeId != null) {
            stmt.bindLong(2, storeId);
        }
 
        Long productId = entity.getProductId();
        if (productId != null) {
            stmt.bindLong(3, productId);
        }
 
        String relationId = entity.getRelationId();
        if (relationId != null) {
            stmt.bindString(4, relationId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StoreProductRelation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long storeId = entity.getStoreId();
        if (storeId != null) {
            stmt.bindLong(2, storeId);
        }
 
        Long productId = entity.getProductId();
        if (productId != null) {
            stmt.bindLong(3, productId);
        }
 
        String relationId = entity.getRelationId();
        if (relationId != null) {
            stmt.bindString(4, relationId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public StoreProductRelation readEntity(Cursor cursor, int offset) {
        StoreProductRelation entity = new StoreProductRelation( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // storeId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // productId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // relationId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StoreProductRelation entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStoreId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setProductId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setRelationId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(StoreProductRelation entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(StoreProductRelation entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(StoreProductRelation entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
